<!--
Initial implementation generated with OpenAI Codex.
Reviewed and modified by Ethan James, including changes to
message styling and sender identification.
-->
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'; import { api, type MeetRequest, type User } from '../services/api'; import { getUsername } from '../services/session'; import AppNav from '../components/AppNav.vue';
const username = getUsername(); const users = ref<User[]>([]); const requests = ref<MeetRequest[]>([]); const requested = ref(new Set<string>()); const showRequests = ref(false); const error = ref('');
async function load() { try { const [people, incoming] = await Promise.all([api.users(), api.meetRequests(username)]); users.value = people.filter((user) => user.username !== username); requests.value = incoming; const states = await Promise.all(users.value.map(async user => ({ user: user.username, value: (await api.hasAcceptedRequest(username, user.username)).hasAcceptedRequest }))); requested.value = new Set(states.filter(state => state.value).map(state => state.user)); } catch { error.value = 'Could not load data. Check the API connection.'; } }
async function requestMeet(receiver: string) { try { await api.sendMeetRequest(username, receiver); requested.value = new Set([...requested.value, receiver]); } catch { error.value = 'Could not send the meeting request.'; } }
async function accept(sender: string) { try { await api.createConnection(username, sender); requests.value = requests.value.filter(request => request.sender !== sender); } catch { error.value = 'Could not accept the meeting request.'; } }
onMounted(load); const title = computed(() => showRequests.value ? 'Meeting requests' : 'People to meet');
</script>
<template><section class="page"><header class="page-header"><div><p class="eyebrow">Collaborate</p><h1>{{ title }}</h1></div><button class="notification" @click="showRequests = !showRequests" aria-label="Meeting requests">🔔<span v-if="requests.length" class="badge">{{ requests.length }}</span></button></header><p v-if="error" class="error">{{ error }}</p><div v-if="showRequests" class="card-list"><article v-for="request in requests" :key="request.sender + request.Time_Of_Send" class="card"><div><strong>@{{ request.sender }}</strong><p class="muted">Sent {{ new Date(request.Time_Of_Send).toLocaleString() }}</p></div><button class="button small" @click="accept(request.sender)">Accept</button></article><p v-if="!requests.length" class="muted">You have no meeting requests.</p></div><div v-else class="card-list"><article v-for="user in users" :key="user.username" class="card"><div class="avatar">{{ user.username.slice(0, 2).toUpperCase() }}</div><div class="grow"><strong>@{{ user.username }}</strong><p class="muted">{{ user.first_name }} {{ user.last_name }}</p></div><button class="button small" :disabled="requested.has(user.username)" @click="requestMeet(user.username)">{{ requested.has(user.username) ? 'Requested' : 'Request to meet' }}</button></article></div><AppNav /></section></template>
